# Copyright (C) 2026 Nik m (@mazurovn)
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"
unmaintained = "none"
unsound = "all"
unused-ignored-advisory = "deny"

ignore = []
