[Service]
ExecStart=
ExecStart=/usr/bin/mazzy-agentd serve --state-dir %h/.local/state/mazzy-agentd --listen 127.0.0.1 --port 9443 --certificate %h/.config/mazzy-agentd/server.crt --private-key %h/.config/mazzy-agentd/server.key --client-ca %h/.config/mazzy-agentd/client-ca.crt --api-socket /run/mazzy-vpn/api-v1.sock
