#!/usr/bin/env bash
# Copyright (C) 2026 Nik m (@mazurovn)
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Downgrade to the package captured by install-release-deb.sh.

set -Eeuo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
ROLLBACK_ROOT="$ROOT/.mazzy/rollback"
check_only=0
if [[ "${1:-}" == --check ]]; then
    check_only=1
    shift
fi
backup="${1:-}"
EXPECTED_PACKAGE=mazzy-vpn-desktop

die() { printf 'rollback-release-deb: %s\n' "$*" >&2; exit 1; }
info() { printf 'rollback-release-deb: %s\n' "$*"; }

for command in dpkg-deb dpkg-query sha256sum systemctl awk; do
    command -v "$command" >/dev/null 2>&1 || die "missing command: $command"
done

if [[ -z "$backup" ]]; then
    [[ -r "$ROLLBACK_ROOT/latest" ]] || die "no saved rollback is available"
    read -r backup <"$ROLLBACK_ROOT/latest"
fi
backup="$(realpath -e -- "$backup")" || die "rollback directory not found"
case "$backup/" in
    "$ROLLBACK_ROOT"/*/) ;;
    *) die "rollback directory is outside $ROLLBACK_ROOT" ;;
esac
[[ -d "$backup" && ! -L "$backup" ]] || die "unsafe rollback directory"
manifest="$backup/manifest.env"
deb="$backup/rollback.deb"
[[ -f "$manifest" && ! -L "$manifest" && -f "$deb" && ! -L "$deb" ]] ||
    die "rollback bundle is incomplete"

# The manifest is generated by our installer, but parse it as data instead of
# sourcing shell text.
value() {
    local key="$1"
    awk -F= -v key="$key" '$1 == key { print substr($0, index($0, "=") + 1); exit }' "$manifest"
}
[[ "$(value schema)" == mazzy-vpn.deb-rollback.v1 ]] || die "unknown manifest schema"
[[ "$(value package)" == "$EXPECTED_PACKAGE" ]] || die "wrong rollback package"
previous_version="$(value previous_version)"
expected_sha="$(value rollback_sha256)"
[[ "$previous_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "invalid previous version"
[[ "$expected_sha" =~ ^[a-f0-9]{64}$ ]] || die "invalid rollback checksum"
[[ "$(sha256sum "$deb" | awk '{print $1}')" == "$expected_sha" ]] ||
    die "rollback DEB checksum mismatch"
[[ "$(dpkg-deb -f "$deb" Package)" == "$EXPECTED_PACKAGE" ]] || die "wrong DEB package"
[[ "$(dpkg-deb -f "$deb" Version)" == "$previous_version" ]] || die "wrong DEB version"

if ((check_only)); then
    info "rollback bundle is valid: $EXPECTED_PACKAGE $previous_version"
    exit 0
fi

before_service="$(systemctl is-active vpnctl.service 2>/dev/null || true)"
info "downgrading $EXPECTED_PACKAGE to $previous_version"
if ((EUID == 0)); then
    apt-get install -y --allow-downgrades -- "$deb"
else
    sudo -v
    sudo apt-get install -y --allow-downgrades -- "$deb"
fi

actual="$(dpkg-query -W -f='${Version}' "$EXPECTED_PACKAGE")"
[[ "$actual" == "$previous_version" ]] || die "rollback installed $actual"

# Restore enablement only; never force a live tunnel stop/start during package
# rollback. Runtime recovery remains an explicit operator decision.
units=(mazzy-vpn-api-recovery.service mazzy-vpn-api.socket vpnctl.service vpnctl-health.timer)
for unit in "${units[@]}"; do
    key="unit_${unit//[^A-Za-z0-9]/_}_enabled"
    wanted="$(value "$key")"
    if [[ "$wanted" == enabled ]]; then
        if ((EUID == 0)); then systemctl enable "$unit" >/dev/null
        else sudo systemctl enable "$unit" >/dev/null; fi
    elif [[ "$wanted" == disabled ]]; then
        if ((EUID == 0)); then systemctl disable "$unit" >/dev/null
        else sudo systemctl disable "$unit" >/dev/null; fi
    fi
done
if ((EUID == 0)); then systemctl daemon-reload
else sudo systemctl daemon-reload; fi

after_service="$(systemctl is-active vpnctl.service 2>/dev/null || true)"
if [[ "$before_service" == active && "$after_service" != active ]]; then
    die "rollback completed, but the previously active VPN service stopped"
fi
info "rollback verified: installed $EXPECTED_PACKAGE $actual"
info "no recovery marker was cleared and no tunnel was deliberately switched"
