[Unit]
Requires=
After=
Wants=mazzy-vpn-api-recovery.service
After=local-fs.target mazzy-vpn-api-recovery.service

[Service]
ExecStart=
ExecStart=/usr/lib/mazzy-vpn/mazzy-vpn _recover-stale-test
TimeoutStartSec=60s
